In [1]:
import numpy as np

In [11]:
a = np.array([[1,2,3],
              [4,5,6]])

In [12]:
b = np.array([[10,11,12],
              [13,14,15]])

In [13]:
sum(a,b)

array([[15, 18, 21],
       [18, 21, 24]])

Q2. Given a numpy array (matrix), how to get a numpy array output which is equal to
the original matrix multiplied by a scalar

In [15]:
b = 2*a

In [16]:
print(b)

[[ 2  4  6]
 [ 8 10 12]]


Q3. Create an identity matrix of dimension 4-by-4.

In [17]:
i = np.eye(3)
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Q4. Convert a 1-D array to a 3-D array

In [23]:
x = np.array([x for x in range(27)])

y = x.reshape((3,3,3))

y

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

Q5. Convert a binary numpy array (containing only 0s and 1s) to a boolean numpy
array

In [24]:
k = np.array([[1, 0, 0],
              [1, 1, 1],
              [0, 0, 0]])

m = k.astype('bool')

m

array([[ True, False, False],
       [ True,  True,  True],
       [False, False, False]])

Q6. Convert all the elements of a numpy array from float to integer datatype

In [25]:
j = np.array([[2.5, 3.8, 1.5],
              [4.7, 2.9, 1.56]])

p = j.astype('int')

p

array([[2, 3, 1],
       [4, 2, 1]])

Q7. Stack 2 numpy arrays horizontally i.e., 2 arrays having the same 1st dimension
(number of rows in 2D arrays)

In [26]:
a1 = np.array([[1,2,3],
               [4,5,6]])

a2 = np.array([[7,8,9],
               [10,11,12]])

l = np.hstack((a1, a2))

l

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

Q8. Output a sequence of equally gapped 5 numbers in the range 0 to 100 (both
inclusive)

In [27]:
g = np.arange(0, 101, 2)

g

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

Q9. Output a matrix (numpy array) of dimension 2-by-3 with each and every value
equal to 5


In [33]:
e = np.full((2, 3), 5)
e

array([[5, 5, 5],
       [5, 5, 5]])

Q10.Given 2 numpy arrays as matrices, output the result of multiplying the 2 matrices
(as a numpy array)


In [34]:
r = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

t = np.array([[2,3,4],
              [5,6,7],
              [8,9,10]])

w = np.matmul(r, t)

w

array([[ 36,  42,  48],
       [ 81,  96, 111],
       [126, 150, 174]])

Q11. Output the array element indexes such that the array elements appear in the
ascending order

In [35]:
array = np.array([46,36,7,9,42])

indexes = np.argsort(array)

indexes

array([2, 3, 1, 4, 0], dtype=int64)

Q12.Multiply a 5x3 matrix by a 3x2 matrix (real matrix product).

In [38]:
q = np.random.rand(5,3)
t = np.random.rand(3,2)
d = np.matmul(q, t)
d

array([[1.63648827, 1.38101946],
       [1.01941586, 0.94133536],
       [1.66922324, 1.33406555],
       [1.81440539, 1.51017199],
       [0.91098344, 0.85660243]])